### ISSUE TITLE
Invalid char in json text

### ISSUE THREAD

**Issue by artod83** [piersyork/owidR#3]
Hello,
I am getting an error fetching the JSON from ourworldindata - worked just fine a couple of days ago.
The error is as follows:

> Error: lexical error: invalid char in json text.
                                       https://ourworldindata.org/grap
                     (right here) ------^

The issue is most likely in line 114 of owid.R:
`data <- jsonlite::fromJSON(data_url)`
As they suggest on [stackoverflow](https://stackoverflow.com/questions/67279373/getting-following-error-in-r-invalid-char-in-json-text), it should be enough to add a readLines(), like this:
`data <- jsonlite::fromJSON(readLines(data_url))`

**Comment by piersyork** [comment]
Hello,

Thanks for flagging this. It looks like Our World in Data have changed the way they load the data json files in their website. I'm currently working on a fix but it means changing the way I parse the data from the site. May take a couple of days.

Best,
Piers

**Comment by piersyork** [comment]
I have updated the development version with a temporary fix. Install using `devtools::install_github("piersyork/owidR")`. Currently you'll only be able to import data that has just one value column.

**Comment by piersyork** [comment]
This has now been fixed and updated on CRAN.

**Comment by artod83** [comment]
Thank you!
