### ISSUE TITLE
error: Problem with `id`

### ISSUE THREAD

**Issue by aarondweinberg** [piersyork/owidR#4]
When I try to import a dataset from owid (e.g., tempdata <- owid("share-graduates-stem-female")), I get the following error:

> Error in `left_join()`:
> ! Join columns in `y` must be present in the data.
> ✖ Problem with `id`.

A backtrace suggests that maybe the `id` label or values are missing?:
>   1. ├─owidR::owid("share-graduates-stem-female")
>   2. │ └─... %>% arrange(entity, year)
>   3. ├─dplyr::arrange(., entity, year)
>   4. ├─dplyr::select(., entity = name, code, year = years, values)
>   5. ├─dplyr::left_join(., entities, by = c(entities = "id"))
>   6. └─dplyr:::left_join.data.frame(., entities, by = c(entities = "id"))
>   7.   └─dplyr:::join_mutate(...)
>   8.     └─dplyr:::join_cols(...)
>   9.       └─dplyr:::check_join_vars(by$y, y_names, by$condition, "y", error_call = error_call)
>  10.         └─rlang::abort(bullets, call = error_call)

**Comment by veggabo** [comment]
> When I try to import a dataset from owid (e.g., tempdata <- owid("share-graduates-stem-female")), I get the following error:
> 
> > Error in `left_join()`:
> > ! Join columns in `y` must be present in the data.
> > ✖ Problem with `id`.
> 
> A backtrace suggests that maybe the `id` label or values are missing?:
> 
> > 1. ├─owidR::owid("share-graduates-stem-female")
> > 2. │ └─... %>% arrange(entity, year)
> > 3. ├─dplyr::arrange(., entity, year)
> > 4. ├─dplyr::select(., entity = name, code, year = years, values)
> > 5. ├─dplyr::left_join(., entities, by = c(entities = "id"))
> > 6. └─dplyr:::left_join.data.frame(., entities, by = c(entities = "id"))
> > 7. └─dplyr:::join_mutate(...)
> > 8. ```
> >    └─dplyr:::join_cols(...)
> >    ```
> > 9. ```
> >      └─dplyr:::check_join_vars(by$y, y_names, by$condition, "y", error_call = error_call)
> >    ```
> > 10. ```
> >         └─rlang::abort(bullets, call = error_call)
> >     ```

Me too, by using the following call:

`redlist_index_id <- "red-list-index"`
`data_redlist <- owid(chart_id = redlist_index_id)`

I get the following error:

> rlang::last_trace(drop = FALSE)
<error/rlang_error>
Error in `left_join()`:
! Join columns in `y` must be present in the data.
x Problem with `id`.

Backtrace:
     x
  1. +-owidR::owid(chart_id = "red-list-index")
  2. | \-... %>% arrange(entity, year)
  3. +-dplyr::arrange(., entity, year)
  4. +-dplyr::select(., entity = name, code, year = years, values)
  5. +-dplyr::left_join(., entities, by = c(entities = "id"))
  6. \-dplyr:::left_join.data.frame(., entities, by = c(entities = "id"))
  7.   \-dplyr:::join_mutate(...)
  8.     \-dplyr:::join_cols(...)
  9.       \-dplyr:::check_join_vars(by$y, y_names, by$condition, "y", error_call = error_call)
 10.         \-rlang::abort(bullets, call = error_call)
 

**Session info:**
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

**Comment by piersyork** [comment]
Thanks both, the problem comes form the way the package fetches the urls for the datasets from the owid website. Due to a small change to the website, this has stopped working. I will fix the bug today and then update the development version. Hopefully it will be fixed on CRAN by next week.

**Comment by piersyork** [comment]
I've uploaded a fix, please install the development version: `devtools::install_github("piersyork/owidR")` Let me know if that hasn't worked. CRAN update will follow.
